// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAPI;

#nullable disable

namespace ProjectAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectAPI.BreakfastFoods", b =>
                {
                    b.Property<int>("Food_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Food_Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Food_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Hot")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommended_Drink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Food_Id");

                    b.ToTable("BreakfastsFoods");

                    b.HasData(
                        new
                        {
                            Food_Id = 1,
                            Calories = 670,
                            Food_Type = "Wrap",
                            Is_Hot = true,
                            Name = "Breakfast Crunchwrap",
                            Recommended_Drink = "Orange Juice"
                        },
                        new
                        {
                            Food_Id = 2,
                            Calories = 250,
                            Food_Type = "?",
                            Is_Hot = true,
                            Name = "?",
                            Recommended_Drink = "?"
                        },
                        new
                        {
                            Food_Id = 3,
                            Calories = 250,
                            Food_Type = "?",
                            Is_Hot = true,
                            Name = "?",
                            Recommended_Drink = "?"
                        },
                        new
                        {
                            Food_Id = 4,
                            Calories = 250,
                            Food_Type = "?",
                            Is_Hot = true,
                            Name = "?",
                            Recommended_Drink = "?"
                        });
                });

            modelBuilder.Entity("ProjectAPI.FavoriteGames", b =>
                {
                    b.Property<int>("Game_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Game_Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hours_Played")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Release_Year")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Game_Id");

                    b.ToTable("FavoriteGames");

                    b.HasData(
                        new
                        {
                            Game_Id = 1,
                            Genre = "Action-Adventure",
                            Hours_Played = 210,
                            Platform = "PC",
                            Release_Year = 2018,
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Game_Id = 2,
                            Genre = "?",
                            Hours_Played = 300,
                            Platform = "?",
                            Release_Year = 2017,
                            Title = "?"
                        },
                        new
                        {
                            Game_Id = 3,
                            Genre = "?",
                            Hours_Played = 300,
                            Platform = "?",
                            Release_Year = 2017,
                            Title = "?"
                        },
                        new
                        {
                            Game_Id = 4,
                            Genre = "?",
                            Hours_Played = 300,
                            Platform = "?",
                            Release_Year = 2017,
                            Title = "?"
                        });
                });

            modelBuilder.Entity("ProjectAPI.Hobbies", b =>
                {
                    b.Property<int>("Hobby_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Hobby_ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobby_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skill_Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weekly_Hours")
                        .HasColumnType("int");

                    b.HasKey("Hobby_ID");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Hobby_ID = 1,
                            Category = "Indoor",
                            Description = "Playing video games with friends",
                            Hobby_Name = "Gaming",
                            Skill_Level = "Intermediate",
                            Weekly_Hours = 17
                        },
                        new
                        {
                            Hobby_ID = 2,
                            Category = "?",
                            Description = "?",
                            Hobby_Name = "?",
                            Skill_Level = "?",
                            Weekly_Hours = 4
                        },
                        new
                        {
                            Hobby_ID = 3,
                            Category = "?",
                            Description = "?",
                            Hobby_Name = "?",
                            Skill_Level = "?",
                            Weekly_Hours = 4
                        },
                        new
                        {
                            Hobby_ID = 4,
                            Category = "?",
                            Description = "?",
                            Hobby_Name = "?",
                            Skill_Level = "?",
                            Weekly_Hours = 4
                        });
                });

            modelBuilder.Entity("ProjectAPI.TeamMembers", b =>
                {
                    b.Property<int>("Team_Member_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Team_Member_Id"));

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("College_Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Favorite_Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year_In_Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Team_Member_Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Team_Member_Id = 1,
                            Birthdate = new DateOnly(2005, 1, 20),
                            College_Program = "Information Technology",
                            Email = "imsickia@mail.uc.edu",
                            Favorite_Color = "Red",
                            Full_Name = "Ian Imsicke",
                            Year_In_Program = "2nd Year"
                        },
                        new
                        {
                            Team_Member_Id = 2,
                            Birthdate = new DateOnly(2000, 9, 2),
                            College_Program = "?",
                            Email = "?",
                            Favorite_Color = "?",
                            Full_Name = "?",
                            Year_In_Program = "?"
                        },
                        new
                        {
                            Team_Member_Id = 3,
                            Birthdate = new DateOnly(2000, 9, 2),
                            College_Program = "?",
                            Email = "?",
                            Favorite_Color = "?",
                            Full_Name = "?",
                            Year_In_Program = "?"
                        },
                        new
                        {
                            Team_Member_Id = 4,
                            Birthdate = new DateOnly(2000, 9, 2),
                            College_Program = "?",
                            Email = "?",
                            Favorite_Color = "?",
                            Full_Name = "?",
                            Year_In_Program = "?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
